import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Main Page',
  description: 'Generated by create next app',
  keywords: 'NEXT APP'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='container'>{children}</div>
      </body>
    </html>
  )
}
